run:
  skip-dirs:
    - docs
    - .github

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  misspell:
    locale: US

linters:
  enable:
    - gofmt
    - golint
    - misspell
#    - gocyclo
  disable:
    - errcheck
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
