linters:
  enable:
    - megacheck
    - govet
    - gocyclo
    - misspell
    - golint

linters-settings:
  gocyclo:
          # minimal code complexity to report, 30 by default (but we recommend 10-20)
          #     min-complexity: 10
    min-complexity: 15
