before:
  hooks:
    - go mod download
builds:
  - id: melody
    main: ./cmd/melody
    binary: melody
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
  - id: meloctl
    main: ./cmd/meloctl
    binary: meloctl
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - 
    files:
      - rules/*
      - etc/*
      - var/*
      - filter.bpf
      - config.yml
      - docker-compose.yml
      - Dockerfile
      - Makefile
    wrap_in_directory: true
    replacements:
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
