name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13", "1.14", "1.15"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -v -p 1 -race -coverprofile=covprofile -covermode=atomic ./...

      - if: ${{ matrix.go == 1.15 }}
        name: Update coverage
        uses: shogo82148/actions-goveralls@v1.4.2
        with:
          path-to-profile: covprofile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
          args: --timeout 5m

  spellcheck:
    name: Spellcheck docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run spellcheck
        run: |
          go get github.com/client9/misspell/cmd/misspell
          misspell -error docs/docs
